#define SERVERFARBE   	"{00AFFF}"                                           //
#define SERVERFARBEHEX  0x00AFFF90                                           //
#define HOST          	""   		    	 			 //
#define SERVERVERSION 	""					    		   	 	 //
#define MAPVERSION    	""                                        //
#define ZEILEN    	    ""                    					 	     //
#define TSIP          	""              					 //
#define TSIP2          	""              					 //
#define WEBURL        	""                       		 	 //
#define WEBURL1       	""                       		     //
#define HOSTINGURL      ""                             	 //
#define HOSTINGURL1     ""                        	 	
#define UCPWEBURL     	""                       		 
#define UCPWEBURL1    	""                       		 	
#define MAXNPC        	""											 
#define BINDIP          ""                                   	
#define CREATER       	""     	 		 						
